spring:
  application:
    name: HSBC-Batch-UseCase
server:
    port: 8081
logging:
    file: 
      path: /Users/sanjaysaini/Desktop/traingContent/itsme/softwares and Bill/fileProcessor
      name: elk-stack1.log

        
        